# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_interface.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13rpc_interface.proto\"\x1b\n\x05\x43hunk\x12\x12\n\npdfContent\x18\x01 \x02(\x0c\"\x1b\n\x07jsonStr\x12\x10\n\x08jsonData\x18\x01 \x02(\t2.\n\x08ParsePDF\x12\"\n\nGetFeature\x12\x06.Chunk\x1a\x08.jsonStr\"\x00(\x01')
)




_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pdfContent', full_name='Chunk.pdfContent', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=50,
)


_JSONSTR = _descriptor.Descriptor(
  name='jsonStr',
  full_name='jsonStr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonData', full_name='jsonStr.jsonData', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['jsonStr'] = _JSONSTR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'rpc_interface_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  ))
_sym_db.RegisterMessage(Chunk)

jsonStr = _reflection.GeneratedProtocolMessageType('jsonStr', (_message.Message,), dict(
  DESCRIPTOR = _JSONSTR,
  __module__ = 'rpc_interface_pb2'
  # @@protoc_insertion_point(class_scope:jsonStr)
  ))
_sym_db.RegisterMessage(jsonStr)



_PARSEPDF = _descriptor.ServiceDescriptor(
  name='ParsePDF',
  full_name='ParsePDF',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=81,
  serialized_end=127,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFeature',
    full_name='ParsePDF.GetFeature',
    index=0,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_JSONSTR,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARSEPDF)

DESCRIPTOR.services_by_name['ParsePDF'] = _PARSEPDF

# @@protoc_insertion_point(module_scope)
